@Author: Rikesh Chhetri

@Date: 2021-07-12 

@Last Modified by: Rikesh Chhetri

@Last Modified time: 2021-07-12 07:03:30

@Title : Program to create an array which looks like below array.

Expected Output:

[[ 0. 0. 0.]

[ 1. 0. 0.]

[ 1. 1. 0.]

[ 1. 1. 1.]]

In [ ]:
from LogHandler import logger
import numpy as np

def create_array():
    try:
        myArray = np.ones((4,3))
        myArray[:1,::1] = 0
        myArray[:2, 1:] = 0
        myArray[:3, 2:] = 0
        logger.info(myArray)

    except Exception as e:
        logger.error(e)

create_array()

@Author: Rikesh Chhetri

@Date: 2021-07-12 

@Last Modified by: Rikesh Chhetri

@Last Modified time: 2021-07-12 07:03:30

@Title : Program to concatenate two 2-dimensional arrays.



In [ ]:
from LogHandler import logger
import numpy as np

def concatenate_2darray():
    try:
        array1 = np.array([[0, 1, 3], [5, 7, 9]])
        array2 = np.array([[0, 2, 4], [6, 8, 10]])
        array3 = np.concatenate((array1,array2),1)
        logger.info(array3)

    except Exception as e:
        logger.error(e)

concatenate_2darray()


@Author: Rikesh Chhetri

@Date: 2021-07-12 

@Last Modified by: Rikesh Chhetri

@Last Modified time: 2021-07-12 07:03:30

@Title : Programto to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.



In [ ]:
from LogHandler import logger
import numpy as np

def display_new_array():
    try:
        array1 = np.arange(0,12).reshape(3,4)
        new_array = array1 * 3
        print("New array after multiplication are: \n ", new_array)

    except Exception as e:
        logger.error(e)

display_new_array()